test:
  cache:
    paths:
      - node_modules/
  image: node:lts-alpine
  script:
    - apk update && apk add --no-cache nmap && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
      chromium \
      harfbuzz \
      "freetype>2.8" \
      ttf-freefont \
      nss
    - yarn --frozen-lockfile
    - npm install -g @ionic/cli
    - yarn build --prod
    - ionic cap copy
    - ionic cap sync android
    - yarn test --code-coverage=true --watch=false --browsers=ChromeHeadless
    - bash <(curl -s https://codecov.io/bash)

docker_build:
  image: docker:20
  services:
    - docker:dind
  script:
    - docker build . -t bic-web
