test:
  cache:
    paths:
      - node_modules/
  image: node:lts-alpine
  script:
    - yarn --frozen-lockfile
    - npm install -g @ionic/cli
    - yarn build --prod
    - ionic cap copy
    - ionic cap sync android
    - yarn test --code-coverage=true --watch=false --browsers=ChromeHeadless
    - bash <(curl -s https://codecov.io/bash)

docker_build:
  image: docker:20
  services:
    - docker:dind
  script:
    - docker build . -t bic-web
