sudo: false

language: node_js
node_js:
  - "12"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-8-jdk
    - lib32stdc++6
    - lib32z1

env:
  CXX=g++-4.8

install:
  - yarn

script:
  - yarn build --prod
  - yarn test --code-coverage=true --watch=false --browsers=ChromeHeadless

after_success:
  - bash <(curl -s https://codecov.io/bash)
