# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: ['22.x', '24.x']
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup Node.js (${{ matrix.node }}) environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: browser-actions/setup-chrome@v2
      - name: Setup
        run: |
          yarn --frozen-lockfile
          npm install -g @ionic/cli
      - name: Build
        run: |
          yarn build --configuration production
          ionic cap copy
          ionic cap sync android
      - name: Test
        run: yarn test --code-coverage=true --watch=false --browsers=ChromeHeadless
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

